steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --cache=true
      - --cache-ttl=24h
      - --destination=asia-northeast1-docker.pkg.dev/studious-journey/studious-journey/web:$COMMIT_SHA
      - --destination=asia-northeast1-docker.pkg.dev/studious-journey/studious-journey/web:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - test-service
      - --image
      - asia-northeast1-docker.pkg.dev/studious-journey/studious-journey/web:$COMMIT_SHA
      - --region
      - asia-northeast1
